language: python
python:
  - "2.7"

env:
  - DJANGO=1.5

install:
  - pip install -q Django==$DJANGO --use-mirrors

script: python setup.py test

notifications:
  email:
    recipients:
      - bjasper@gmail.com
